FROM node:20-bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate && chmod +x docker-entrypoint.sh
EXPOSE 3355
CMD ["./docker-entrypoint.sh"]
